# Generated by Django 5.0.3 on 2024-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaapi', '0003_album_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_covers/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
